### ISSUE TITLE
테스트 작성 시 레디스 관련 버그

### ISSUE THREAD

**Issue by vectorch9** [Instagram-Clone-Coding/Spring_instagram-clone#196]
## Describe the bug
- Repository를 테스트 하기 위해 의존성 주입 시 RedisRepository 관련 에러 발생.
- **에러메시지 일부**
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'cloneproject.Instagram.domain.story.repository.MemberStoryRedisRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1790) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1346) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.9.jar:5.3.9]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.9.jar:5.3.9]
	... 88 common frames omitted
```
- TestConfig에 RedisServer, Template 관련 코드를 추가해도 같은 문제 발생
- MemberRedisRepository를 주입해주어야 하는데 아마 @DataJpaTest의 대상에 포함되지 않는 것 같음
- MemberRedisRepository를 직접 Bean으로 만들까 생각해보았으나 구현 클래스가 없는 interface라 불가능

## To Reproduce
```
// MemberRepositoryTest.java
@DataJpaTest
@Import(TestConfig.class)
@ActiveProfiles("testing")
public class MemberRepositoryTest {

	@Autowired
	private MemberRepository memberRepository;

	@Test
	void test() {
		assertEquals(-1, -1);
	}

}
```
```
// TestConfig.java
@TestConfiguration
public class TestConfig {

	@Bean
	public JPAQueryFactory jpaQueryFactory(EntityManager entityManager) {
		return new JPAQueryFactory(entityManager);
	}

}

```

## Expected behavior
-

**Comment by vectorch9** [comment]
- Issue로 작성하다가 방법을 발견해 셀프 답변합니다
```
@DataJpaTest
@Import(TestConfig.class)
@ActiveProfiles("testing")
public class MemberRepositoryTest {

	@MockBean
	private MemberStoryRedisRepository memberStoryRedisRepository;

	@Autowired
	private MemberRepository memberRepository;

	@Test
	void test() {
		assertEquals(-1, -1);
	}

}
```
- 위와 같이 `@MockBean`을 추가하면 가짜 Bean을 만들어줘 해결되네요

**Comment by vectorch9** [comment]
@seonpilKim 해결된 이슈지만, `TestConfig`와 `@Import(TestConfig.class)`을 통해 `JPAQueryFactory`를 주입받는게 적절한 방식인지 잘 모르겠네요

**Comment by vectorch9** [comment]
추가로, Repository를 테스트 할 땐 직접 작성한 Jdbc와 querydsl만 테스트하면 되겠죠?

**Comment by seonpilKim** [comment]
@bluetifulc 

> 해결된 이슈지만, TestConfig와 @Import(TestConfig.class)을 통해 JPAQueryFactory를 주입받는게 적절한 방식인지 잘 모르겠네요

여러 Repository를 하나의 클래스에서 테스트하는 것 보다, 각각 나누어서 테스트하는 것을 추천드립니다.

일일이 클래스마다 `@ActiveProfiles`을 붙이는 것 보다, test 모듈에 application.yml을 생성해서 spring.profiles.active=test를 추가하고, application-test.yml에 관련 설정들을 넣으면, 테스트 코드 작성 시 더 편리할 것 같아요.

별도로 TestConfig.java를 추가하지 않고, `@Import(QuerydslConfig.class)`를 사용해도 될 것 같아요.

> 추가로, Repository를 테스트 할 땐 직접 작성한 Jdbc와 querydsl만 테스트하면 되겠죠?

Repository 계층 테스트는 SpringDataJPA가 기본적으로 제공하는 메소드를 제외하고, `메소드 이름을 이용한 쿼리 생성 메소드, JPQL, jdbc, querydsl, redis` 이 정도로 테스트하면 좋을 것 같습니다.

아, 그리고 story 도메인은 제가 담당하고 있으니 MemberStoryRedisRepository 테스트는 제가 얼른 작성해서 PR 올리도록 하겠습니다!
